# Diagnóstico e customização de bi- e trigrams da filosofia####
# Método de frequência
# Bigrams
stop_pt <- tidytext::get_stopwords("pt")
bidados <- dados |> 
  tidytext::unnest_tokens(bigram, DS_RESUMO, token = "ngrams", n = 2) # Formação da variável bigram com todas palavras do resumo
bidados_sep <- bidados  |>   
  tidyr::separate(bigram, into = c("word1", "word2"), sep = " ") # Separação dos bigrams para remoção de stopwords
filobigrams <- bidados_sep |> 
  dplyr::filter(!word1 %in% stop_pt$word, # Remoção de stopwords em bigrams
         !word2 %in% stop_pt$word) |> # Remoção de stopwords em bigrams
  tidyr::unite("bigram", c(word1, word2), sep = " ") |> # Unificação dos bigrams novamente
  dplyr::count(bigram, sort = TRUE) |> # Contagem da frequência absoluta de cada bigram
  dplyr::filter(n >= 29) # Filtragem de bigrams com 29 ou mais ocorrências (n = 1019)

# Salvar tabela com bigrams da filosofia
filobigrams |>
  readr::write_csv("dados/filobigrams.csv")

# Trigrams
tridados <- dados |> 
  tidytext::unnest_tokens(trigram, DS_RESUMO, token = "ngrams", n = 3) # Formação da variável trigram com todas palavras do resumo
tridados_sep <- tridados  |>   
  tidyr::separate(trigram, into = c("word1", "word2", "word3"), sep = " ") # Separação dos trigrams para remoção de stopwords
filotrigrams <- tridados_sep |> 
  dplyr::filter(!word1 %in% stop_pt$word, 
                !word2 %in% stop_pt$word,
                !word3 %in% stop_pt$word) |> # Remoção de stopwords em trigrams
  tidyr::unite("trigram", c(word1, word2, word3), sep = " ") |> # Unificação dos trigrams novamente
  dplyr::count(trigram, sort = TRUE) |> # Contagem da frequência absoluta de cada trigram
  dplyr::filter(n >= 5) # Filtragem de bigrams com 10 ou mais ocorrências (n = 909)

# Salvar tabela com trigrams da filosofia
filotrigrams |>
  readr::write_csv("dados/filotrigrams.csv")

#Incorporação de bi- e trigrams relevantes na variável DS_RESUMO####
filongrams <- c(
  #####Trigrams relevantes com até 05 ocorrências | Arquivo: dados/filotrigrams.csv##
  "humano demasiado humano", 
  "assim falou zaratustra",
  "animais nao humanos",
  "sine qua non",
  "todos contra todos",
  "letre et le neant",
  "sein und zeit",
  "assim falava zaratustra", 
  "theory of justice", 
  #####Bigrams relevantes com até 10 ocorrências | Arquivo: dados/filobigrams.csv##
  "ser humano ",
  "natureza humana",
  "filosofia politica",
  "seculo xx",
  "razao pura",
  "filosofia moral",
  "seculo xix",
  "pensamento politico",
  "direitos humanos",
  "teoria critica",
  "razao pratica",
  "seculo xviii",
  "si mesma",
  "seres humanos",
  "condicao humana",
  "sociedade civil",
  "vida humana",
  "filosofia pratica",
  "direito natural",
  "teoria politica",
  "contrato social",
  "acao humana",
  "eterno retorno",
  "existencia humana",
  "lei moral",
  "esfera publica",
  "acao politica",
  "imperativo categorico",
  "economia politica",
  "identidade pessoal",
  "conhecimento cientifico",
  "santo agostinho",
  "lei natural",
  "ontologia fundamental",
  "teoria moral",
  "ciencias humanas",
  "pensamento ocidental",
  "hermeneutica filosofica",
  "investigacoes filosoficas",
  "seculo xvii",
  "analitica existencial",
  "acoes humanas",
  "espaco publico",
  "ciencia cognitiva",
  "tractatus logicophilosophicus",
  "bem comum",
  "ciencias naturais",
  "estado civil",
  "filosofia moderna",
  "filosofia transcendental",
  "idealismo transcendental",
  "livro i",
  "poder politico",
  "sumo bem",
  "dignidade humana",
  "paz perpetua",
  "filosofia critica",
  "industria cultural",
  "vida politica",
  "ciencia moderna",
  "estados mentais",
  "acao moral",
  "corpo politico",
  "liberalismo politico",
  "tecnica moderna",
  "filosofia analitica",
  "mundo sensivel",
  "sociedade moderna",
  "pessoa humana",
  "vontade livre",
  "antropologia filosofica",
  "deducao transcendental",
  "liberdade politica",
  "poder soberano",
  "filosofia primeira",
  "especie humana",
  "liberdade individual",
  "idealismo alemao",
  "metodo dialetico",
  "responsabilidade moral",
  "vida feliz",
  "espirito livre",
  "homem moderno",
  "juizos morais",
  "moral kantiana",
  "nomes proprios",
  "santo tomas",
  "teoria freudiana",
  "agir comunicativo",
  "consciencia moral",
  "posicao original",
  "seculo xvi",
  "acao comunicativa",
  "dialetica negativa",
  "gaia ciencia",
  "justica social",
  "propriedade privada",
  "razao suficiente",
  "agir humano",
  "metodo fenomenologico",
  "sociedade contemporanea",
  "sabedoria pratica",
  "cultura ocidental",
  "mundo exterior",
  "ordem social",
  "positivismo juridico",
  "teoria psicanalitica",
  "arte contemporanea",
  "estado moderno",
  "inteligencia artificial",
  "razao instrumental",
  "vida nua",
  "arte moderna",
  "ciencias sociais",
  "comunidade politica",
  "experiencia humana",
  "pensamento metafisico",
  "seculo xxi",
  "virtude moral",
  "arte tragica",
  "livre arbitrio",
  "processo historico",
  "aparelho psiquico",
  "behaviorismo radical",
  "dialetica hegeliana",
  "emancipacao humana",
  "entendimento humano",
  "essencia humana",
  "logica classica",
  "meio ambiente",
  "metafisica tradicional",
  "metodo cientifico",
  "racionalidade cientifica",
  "realidade social",
  "realismo cientifico",
  "selecao natural",
  "materialismo historico",
  "si mesmos",
  "comportamento humano",
  "cultura moderna",
  "direitos fundamentais",
  "primeiros principios",
  "razao humana",
  "sociedade capitalista",
  "atividade humana",
  "filosofia cartesiana",
  "filosofia natural",
  "idade media",
  "mundo externo",
  "mundos possiveis",
  "pensamento etico",
  "pensamento moderno",
  "principios metafisicos",
  "sentimentos morais",
  "seres vivos",
  "realidade objetiva",
  "revolucao francesa",
  "valor moral",
  "concepcao politica",
  "filosofia platonica",
  "grecia antiga",  
  "ontologia fenomenologica",
  "razao publica",
  "religiao crista",
  "si mesmas",
  "teoria etica",
  "ecce homo",
  "educacao estetica",
  "filosofia teorica",
  "genero humano",
  "mal radical",
  "mundo natural",
  "revolucoes cientificas",
  "boa vontade",
  "etica aristotelica",
  "filosofia ocidental",
  "forma logica",
  "investigacoes logicas",
  "atitude critica",  
  "conduta humana",
  "direito positivo",
  "estatuto ontologico",
  "historia natural",
  "leis naturais",
  "mundo moderno",
  "pacto social",
  "sistema juridico",
  "tragedia grega",
  "vida boa",
  "vontade humana",
  "animais naohumanos",
  "dialetica transcendental",
  "estados unidos",
  "livro x",
  "principio moral",
  "principio supremo",
  "psicanalise freudiana",
  "sociedade democratica",
  "conhecimento objetivo",
  "desobediencia civil",
  "fenomenologia husserliana",
  "filosofia antiga",
  "filosofia grega",
  "mecanica quantica",
  "ordem politica",
  "si proprio",
  "sociedade industrial",
  "teoria social",
  "vida cotidiana",
  "bem supremo",
  "drama barroco",
  "historia universal",
  "problema mentecorpo",
  "representacoes mentais",
  "sistema capitalista",
  "soberania popular",
  "amor fati",
  "discurso moral",
  "ilusao transcendental",
  "logica modal",
  "mundo fisico",
  "organizacao social",
  "relacoes internacionais",
  "transformacao social",
  "ciencias cognitivas",
  "consequencia logica",
  "critica imanente",
  "estado social",
  "filosofia aristotelica",
  "instituicoes politicas",
  "instituicoes sociais",
  "pesquisa cientifica",
  "primeiro principio",
  "principios fundamentais",
  "projeto politico",
  "representacao politica",
  "sociedades democraticas",
  "agir moral",
  "antiguidade classica",
  "ideologia alema",
  "justificacao epistemica",
  "revolucao cientifica",
  "sexto empirico",
  "sistema hegeliano",
  "teoria kantiana",
  "terceira critica",
  #Bigrams para exclusão (reconhecidos após rodar alguns modelos STM)
  "diz respeito",
  "outro lado",
  "santa maria")

# Salvar vetor para uso em stm_filosofia.R
readr::write_lines(filongrams, "dados/filograms")
